### ISSUE TITLE
Project name: More than 1 project has the same names

### ISSUE THREAD

**Issue by DanilchukV** [mifort-org/mifort-timesheet#297]
Chrome 56.0.2924.87 (64-bit); OS Win 7 Proffessional
**_Steps:_**
1. Open tab "Project"
2. Add two new project
3. Name the projects the same
4. Reload the page

**_Result:_**
![nazvanie proekta_300x153](https://cloud.githubusercontent.com/assets/26150007/23947242/921f40b8-0986-11e7-9a63-53dbb2d72ed6.png)
![nazvanie proekta2_300x433](https://cloud.githubusercontent.com/assets/26150007/23947241/921d1220-0986-11e7-9ec7-47c3251bbea8.png)
**_Expected result:_**
More than 1 project has not the same names

**Comment by JaneKamneva** [comment]
Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit);
OS: Linux Ubuntu 14.04
The problem is urgent.
![selection_019](https://user-images.githubusercontent.com/26093980/28073351-1b8b9142-665e-11e7-9d0e-827c2074c51b.png)
![selection_020](https://user-images.githubusercontent.com/26093980/28073362-203f09bc-665e-11e7-9043-1a7bf38c3219.png)

**Comment by AlexDormash** [comment]
fix -  More than 1 project has not the same names
