### ISSUE TITLE
Tab "Calendar" : Markup is broken when adding new Custom Day

### ISSUE THREAD

**Issue by DanilchukV** [mifort-org/mifort-timesheet#306]
Chrome 56.0.2924.87 (64-bit); OS Win 7 Proffessional
**_Steps:_**
1. Open tab "Calendar"
2. Add more than 10 new "Custom Days"
3. Reload the page

**_Result:_**
![screenshot_2_305x528](https://cloud.githubusercontent.com/assets/26150007/24125904/ba90d650-0dd3-11e7-828d-8967be7ddbab.png)
**_Expected result:_**
![screenshot_305x229](https://cloud.githubusercontent.com/assets/26150007/24126308/e8590e7a-0dd5-11e7-9af3-90fc1512eb4d.png)

**Comment by JaneKamneva** [comment]
Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit); 
OS: Linux Ubuntu 14.04
The problem is available. The point is that the spectrum of colors of the hexagon appears when a user does next actions:
1. click one time on hexagon in a new "Custom Day"
2. then click on any another hexagon.

Expected result: the spectrum of colors of the hexagon must be available immediately when user add a new "Custom Day"
